In [ ]:
# pandas

In [ ]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10,20,30])

In [ ]:
s

0    10
1    20
2    30
dtype: int64

In [ ]:
s = pd.Series([10,20,30], index=['a','b','c'])

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
# dictionary

In [ ]:
 {'name': 'tanishka', 'age': 19, 'Marks' :20}

{'name': 'tanishka', 'age': 19, 'Marks': 20}

In [ ]:
s = pd.Series(s)

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
s = pd.Series(5,index = [0,1,2,3,3])

In [ ]:
s

0    5
1    5
2    5
3    5
3    5
dtype: int64

In [ ]:
# Attributes

In [ ]:
s = pd.Series([10,20,30], index=['a','b','c'])

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
s.values

array([10, 20, 30])

In [ ]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.shape

(3,)

In [ ]:
s*2

a    20
b    40
c    60
dtype: int64

In [ ]:
s = pd.Series([1,None,3])

In [ ]:
s

0    1.0
1    NaN
2    3.0
dtype: float64

In [ ]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [ ]:
s.dropna()

0    1.0
2    3.0
dtype: float64

In [ ]:
s.fillna(s)

0    1.0
1    NaN
2    3.0
dtype: float64

In [ ]:
s = pd.Series([1,2,2,3,3,3])

In [ ]:
s

0    1
1    2
2    2
3    3
4    3
5    3
dtype: int64

In [ ]:
s.value_counts()

3    3
2    2
1    1
Name: count, dtype: int64

In [ ]:
s = pd.Series([10,20,30,40,], index=['a','b','c','d'])

In [ ]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
s = pd.Series([10,20,30,40])

In [ ]:
data = {
    "Name": ["Rahul", "Priya", "Amit"],
    "Age": [25, 30, 28],
    "City": ["Pune", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)

In [ ]:
data

{'Name': ['Rahul', 'Priya', 'Amit'],
 'Age': [25, 30, 28],
 'City': ['Pune', 'Mumbai', 'Delhi']}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age    City
0  Rahul   25    Pune
1  Priya   30  Mumbai
2   Amit   28   Delhi

In [ ]:
data = {
    "Subject": ["Math", "Science", "English", "History", "Computer"],
    "Marks": [95, 88, 76, 82, 91],
    "Grade": ["A+", "A", "B", "B+", "A+"]
}
df = pd.DataFrame(data)

In [ ]:
data

{'Subject': ['Math', 'Science', 'English', 'History', 'Computer'],
 'Marks': [95, 88, 76, 82, 91],
 'Grade': ['A+', 'A', 'B', 'B+', 'A+']}

In [ ]:
df

    Subject  Marks Grade
0      Math     95    A+
1   Science     88     A
2   English     76     B
3   History     82    B+
4  Computer     91    A+

In [ ]:
df.to_csv('marks_data.csv', index=False)

In [ ]:
df = pd.read_csv("marks_data.csv")

In [ ]:
df

    Subject  Marks Grade
0      Math     95    A+
1   Science     88     A
2   English     76     B
3   History     82    B+
4  Computer     91    A+

In [ ]:
df.head()

    Subject  Marks Grade
0      Math     95    A+
1   Science     88     A
2   English     76     B
3   History     82    B+
4  Computer     91    A+

In [ ]:
df.tail()

    Subject  Marks Grade
0      Math     95    A+
1   Science     88     A
2   English     76     B
3   History     82    B+
4  Computer     91    A+

In [ ]:
df.columns

Index(['Subject', 'Marks', 'Grade'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  5 non-null      object
 1   Marks    5 non-null      int64
 2   Grade    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [ ]:
df.describe()

           Marks
count   5.000000
mean   86.400000
std     7.503333
min    76.000000
25%    82.000000
50%    88.000000
75%    91.000000
max    95.000000

In [ ]:
df.isnull().sum()

Subject    0
Marks      0
Grade      0
dtype: int64

In [ ]:
df =df.drop_duplicates()

In [ ]:
df

    Subject  Marks Grade
0      Math     95    A+
1   Science     88     A
2   English     76     B
3   History     82    B+
4  Computer     91    A+

In [ ]:
df['Marks'] = df['Marks'].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  5 non-null      object
 1   Marks    5 non-null      int64
 2   Grade    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [ ]:
df["Subject"]

0        Math
1     Science
2     English
3     History
4    Computer
Name: Subject, dtype: object

In [ ]:
df[["Subject","Grade"]]

    Subject Grade
0      Math    A+
1   Science     A
2   English     B
3   History    B+
4  Computer    A+

In [ ]:
df= df.sort_values(by="Marks", ascending=False)

In [ ]:
df

    Subject  Marks Grade
0      Math     95    A+
4  Computer     91    A+
1   Science     88     A
3   History     82    B+
2   English     76     B